projects:
  InTouchAPI-develop:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: th3rlrvc2rgulgzv67fhwc4l5m
        maxDepth: 2
extensions:
  amplify:
    version: 3
