projects:
  ITAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: lyc4vogonffh3ik7z4365r6kiu
        maxDepth: 2
extensions:
  amplify:
    version: 3
