// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:553b3a6f-ac12-4405-becf-a62e77a32388",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_a4mFnWPuQ",
    "aws_user_pools_web_client_id": "bocgntqf04o88ckncs3p0f3kt",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ofuzn6vnvjhl3fkrap4af4lg7a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
