// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2872e556-bff2-41a6-b6d8-4f77f4ddd8e2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8dwHH2Mlu",
    "aws_user_pools_web_client_id": "36isq9skn9gpnorri6sl0pu8le",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://65jtee52undjley5jvlksvvowi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yilslt7bdrdj5gkrgatapiemgy"
};


export default awsmobile;
